from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import uvicorn
import duckdb
import json

app = FastAPI()

# Enable CORS for the frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  
    allow_credentials=True,
    allow_methods=["*"],  
    allow_headers=["*"],
)

# Initialize DuckDB connection to query the local CSV File generated by Pandas
conn = duckdb.connect()

@app.get("/api/rankings")
async def get_rankings():
    try:
        # Utilizing DuckDB to instantly parse and query the mock GDELT CSV
        query = "SELECT * FROM read_csv_auto('mock_rankings.csv') ORDER BY rank ASC"
        df = conn.execute(query).df()
        
        # Convert DataFrame to list of dicts suitable for the frontend
        rankings = []
        for _, row in df.iterrows():
            rankings.append({
                "rank": int(row["rank"]),
                "name": str(row["name"]),
                "category": str(row["category"]),
                "visibility": int(row["visibility"]),
                "growth": str(row["growth"]),
                "history": json.loads(str(row["history"])),
                "recent_reviews": json.loads(str(row["recent_reviews"])),
                "sentiment": str(row["sentiment"])
            })
        return rankings
    except Exception as e:
        print(f"Database error: {e}")
        return {"error": "Ensure you have run data_generator.py first."}

@app.get("/api/categories")
async def get_categories():
    try:
        query = "SELECT DISTINCT category FROM read_csv_auto('mock_rankings.csv')"
        categories = conn.execute(query).df()["category"].tolist()
        return categories
    except Exception:
        return []

@app.get("/")
async def root():
    return {"status": "FastAPI DuckDB Backend is running successfully"}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
